name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    
    - name: Install dependencies
      run: go mod tidy
    
    - name: Run unit tests
      run: go test -v -short ./pkg/...
    
    - name: Build
      run: go build -o bin/golisp cmd/golisp/main.go
